[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
headless = true
runOnSave = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
fastReruns = true
